import { Translations, Language } from './types';

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    title: 'Note Master',
    subtitle: 'Master reading notes on the staff',
    setupTitle: 'Setup Practice',
    selectLanguage: 'Language',
    selectClef: 'Select Clef',
    selectOctaves: 'Select Octaves',
    selectNotes: 'Select Notes',
    startSession: 'Start Practice',
    correct: 'Correct',
    total: 'Total',
    accuracy: 'Accuracy',
    streak: 'Streak',
    trebleClef: 'Treble Clef',
    bassClef: 'Bass Clef',
    question: 'What note is this?',
    finishSession: 'Finish Session',
    resultsTitle: 'Session Results',
    sessionSummary: 'Great job! Here is how you performed.',
    startNewSession: 'Start New Session',
    correctAnswer: 'Correct!',
    incorrectAnswer: 'Incorrect. It was',
    octave: 'Octave',
    noOctavesSelected: 'Please select at least one octave.',
    noNotesSelected: 'Please select at least one note.',
    avgTime: 'Avg Time',
    statNote: 'Note',
    statAccuracy: 'Accuracy',
    statTime: 'Time',
    sortBy: 'Sort by',
    sortDifficulty: 'Difficulty',
    sortName: 'Name',
    sortTime: 'Time'
  },
  ru: {
    title: 'Мастер Нот',
    subtitle: 'Тренажёр чтения с листа',
    setupTitle: 'Настройка',
    selectLanguage: 'Язык',
    selectClef: 'Ключ',
    selectOctaves: 'Выберите октавы',
    selectNotes: 'Выберите ноты',
    startSession: 'Начать',
    correct: 'Верно',
    total: 'Всего',
    accuracy: 'Точность',
    streak: 'Серия',
    trebleClef: 'Скрипичный',
    bassClef: 'Басовый',
    question: 'Какая это нота?',
    finishSession: 'Завершить',
    resultsTitle: 'Результаты',
    sessionSummary: 'Отличная работа! Вот ваши результаты.',
    startNewSession: 'Новая тренировка',
    correctAnswer: 'Верно!',
    incorrectAnswer: 'Ошибка. Это была',
    octave: 'Октава',
    noOctavesSelected: 'Выберите хотя бы одну октаву.',
    noNotesSelected: 'Выберите хотя бы одну ноту.',
    avgTime: 'Ср. время',
    statNote: 'Нота',
    statAccuracy: 'Точность',
    statTime: 'Время',
    sortBy: 'Сортировка',
    sortDifficulty: 'Сложность',
    sortName: 'Имя',
    sortTime: 'Время'
  },
  uk: {
    title: 'Майстер Нот',
    subtitle: 'Тренажер читання з листа',
    setupTitle: 'Налаштування',
    selectLanguage: 'Мова',
    selectClef: 'Ключ',
    selectOctaves: 'Оберіть октави',
    selectNotes: 'Оберіть ноти',
    startSession: 'Почати',
    correct: 'Вірно',
    total: 'Всього',
    accuracy: 'Точність',
    streak: 'Серія',
    trebleClef: 'Скрипковий',
    bassClef: 'Басовий',
    question: 'Яка це нота?',
    finishSession: 'Завершити',
    resultsTitle: 'Результати',
    sessionSummary: 'Чудова робота! Ось ваші результати.',
    startNewSession: 'Нове тренування',
    correctAnswer: 'Вірно!',
    incorrectAnswer: 'Помилка. Це була',
    octave: 'Октава',
    noOctavesSelected: 'Оберіть хоча б одну октаву.',
    noNotesSelected: 'Оберіть хоча б одну ноту.',
    avgTime: 'Сер. час',
    statNote: 'Нота',
    statAccuracy: 'Точність',
    statTime: 'Час',
    sortBy: 'Сортувати',
    sortDifficulty: 'Складність',
    sortName: 'Назва',
    sortTime: 'Час'
  },
  et: {
    title: 'Noodimeister',
    subtitle: 'Õpi noote lugema',
    setupTitle: 'Seadistus',
    selectLanguage: 'Keel',
    selectClef: 'Võti',
    selectOctaves: 'Vali oktavid',
    selectNotes: 'Vali noodid',
    startSession: 'Alusta',
    correct: 'Õige',
    total: 'Kokku',
    accuracy: 'Täpsus',
    streak: 'Seeria',
    trebleClef: 'Viiulivõti',
    bassClef: 'Bassivõti',
    question: 'Mis noot see on?',
    finishSession: 'Lõpeta',
    resultsTitle: 'Tulemused',
    sessionSummary: 'Hästi tehtud! Siin on sinu tulemused.',
    startNewSession: 'Uus treening',
    correctAnswer: 'Õige!',
    incorrectAnswer: 'Vale. See oli',
    octave: 'Oktav',
    noOctavesSelected: 'Palun vali vähemalt üks oktav.',
    noNotesSelected: 'Palun vali vähemalt üks noot.',
    avgTime: 'Keskm. aeg',
    statNote: 'Noot',
    statAccuracy: 'Täpsus',
    statTime: 'Aeg',
    sortBy: 'Sorteeri',
    sortDifficulty: 'Raskus',
    sortName: 'Nimi',
    sortTime: 'Aeg'
  }
};

export const NOTE_NAMES: import('./types').NoteName[] = ['C', 'D', 'E', 'F', 'G', 'A', 'B'];

export const OCTAVE_RANGES = {
  treble: [3, 4, 5, 6],
  bass: [1, 2, 3, 4]
};