import type { Translations, Language, NoteName } from './types';

export const APP_NAME = 'notemeister';
export const BASE_URL = `/${APP_NAME}/`;

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    title: 'Note Master',
    subtitle: 'Master reading notes on the staff',
    setupTitle: 'Setup Practice',
    selectLanguage: 'Language',
    selectClef: 'Select Clef',
    selectOctaves: 'Select Octaves',
    selectNotes: 'Select Notes',
    selectTempo: 'Select Tempo',
    tempoSlow: 'Slow',
    tempoNormal: 'Normal',
    tempoFast: 'Fast',
    startSession: 'Start Practice',
    correct: 'Correct',
    total: 'Total',
    accuracy: 'Accuracy',
    streak: 'Streak',
    trebleClef: 'Treble Clef',
    bassClef: 'Bass Clef',
    question: 'What note is this?',
    playOrSing: 'Play or sing',
    playThisNote: 'Play this note',
    finishSession: 'Finish Session',
    resultsTitle: 'Session Results',
    sessionSummary: 'Great job! Here is how you performed.',
    startNewSession: 'Start New Session',
    correctAnswer: 'Correct!',
    incorrectAnswer: 'Incorrect. It was',
    octave: 'Octave',
    noOctavesSelected: 'Please select at least one octave.',
    noNotesSelected: 'Please select at least one note.',
    avgTime: 'Avg Time',
    statNote: 'Note',
    statAccuracy: 'Accuracy',
    statTime: 'Time',
    sortBy: 'Sort by',
    sortDifficulty: 'Difficulty',
    sortName: 'Name',
    sortTime: 'Time',
    selectInstrument: 'Select Instrument',
    instrumentSilence: 'Silence',
    instrumentPiano: 'Piano',
    instrumentGuitar: 'Guitar',
    instrumentFlute: 'Flute',
    instrumentMicrophone: 'Microphone',
    micAccessRequired: 'Microphone access is required for pitch detection.',
    performanceAnalysis: 'Performance Analysis',
    concealDetails: 'Conceal Details',
    viewDeepMetrics: 'View Deep Metrics',
    focusOn: 'Focus on:',
    feedbackMastery: 'Absolute Mastery! Your precision is flawless.',
    feedbackExemplary: "Exemplary! You're becoming highly fluent.",
    feedbackProgress: 'Great Progress! Keep honing that muscle memory.',
    feedbackGettingThere: 'Getting There! Focus on accuracy over speed.',
    feedbackKeepPracticing: 'Keep Practicing! Every session builds your skill.',
    quoteExpert: 'Expert performance! Your hard work is clearly paying off. 🎹',
    quoteStrong: "Strong progress! You're building a solid foundation. 🎵",
    quoteConsistency: 'Consistency is key. Keep playing and your fingers will find the way! ✨',
    reviewProgress: 'Review Progress',
    backToOverview: 'Back to Overview',
  },
  ru: {
    title: 'Мастер Нот',
    subtitle: 'Тренажёр чтения с листа',
    setupTitle: 'Настройка',
    selectLanguage: 'Язык',
    selectClef: 'Ключ',
    selectOctaves: 'Выберите октавы',
    selectNotes: 'Выберите ноты',
    selectTempo: 'Темп',
    tempoSlow: 'Медленно',
    tempoNormal: 'Нормально',
    tempoFast: 'Быстро',
    startSession: 'Начать',
    correct: 'Верно',
    total: 'Всего',
    accuracy: 'Точность',
    streak: 'Серия',
    trebleClef: 'Скрипичный',
    bassClef: 'Басовый',
    question: 'Какая это нота?',
    playOrSing: 'Сыграйте или спойте',
    playThisNote: 'Сыграйте эту ноту',
    finishSession: 'Завершить',
    resultsTitle: 'Результаты',
    sessionSummary: 'Отличная работа! Вот ваши результаты.',
    startNewSession: 'Новая тренировка',
    correctAnswer: 'Верно!',
    incorrectAnswer: 'Ошибка. Это была',
    octave: 'Октава',
    noOctavesSelected: 'Выберите хотя бы одну октаву.',
    noNotesSelected: 'Выберите хотя бы одну ноту.',
    avgTime: 'Ср. время',
    statNote: 'Нота',
    statAccuracy: 'Точность',
    statTime: 'Время',
    sortBy: 'Сортировка',
    sortDifficulty: 'Сложность',
    sortName: 'Имя',
    sortTime: 'Время',
    selectInstrument: 'Инструмент',
    instrumentSilence: 'Без звука',
    instrumentPiano: 'Пианино',
    instrumentGuitar: 'Гитара',
    instrumentFlute: 'Флейта',
    instrumentMicrophone: 'Микрофон',
    micAccessRequired: 'Для определения высоты звука требуется доступ к микрофону.',
    performanceAnalysis: 'Анализ исполнения',
    concealDetails: 'Скрыть детали',
    viewDeepMetrics: 'Глубокая аналитика',
    focusOn: 'Фокус на:',
    feedbackMastery: 'Абсолютное мастерство! Ваша точность безупречна.',
    feedbackExemplary: 'Превосходно! Вы становитесь очень беглым.',
    feedbackProgress: 'Отличный прогресс! Продолжайте оттачивать память.',
    feedbackGettingThere: 'Уже близко! Сосредоточьтесь на точности, а не на скорости.',
    feedbackKeepPracticing: 'Продолжайте практиковаться! Каждая сессия развивает навык.',
    quoteExpert: 'Мастерское исполнение! Ваша работа приносит плоды. 🎹',
    quoteStrong: 'Сильный прогресс! Вы строите прочный фундамент. 🎵',
    quoteConsistency: 'Постоянство — залог успеха. Продолжайте играть! ✨',
    reviewProgress: 'Просмотр прогресса',
    backToOverview: 'Вернуться к обзору',
  },
  uk: {
    title: 'Майстер Нот',
    subtitle: 'Тренажер читання з листа',
    setupTitle: 'Налаштування',
    selectLanguage: 'Мова',
    selectClef: 'Ключ',
    selectOctaves: 'Оберіть октави',
    selectNotes: 'Оберіть ноти',
    selectTempo: 'Темп',
    tempoSlow: 'Повільно',
    tempoNormal: 'Нормально',
    tempoFast: 'Швидко',
    startSession: 'Почати',
    correct: 'Вірно',
    total: 'Всього',
    accuracy: 'Точність',
    streak: 'Серія',
    trebleClef: 'Скрипковий',
    bassClef: 'Басовий',
    question: 'Яка це нота?',
    playOrSing: 'Зіграйте або заспівайте',
    playThisNote: 'Зіграйте цю ноту',
    finishSession: 'Завершити',
    resultsTitle: 'Результати',
    sessionSummary: 'Чудова робота! Ось ваші результати.',
    startNewSession: 'Нове тренування',
    correctAnswer: 'Вірно!',
    incorrectAnswer: 'Помилка. Це була',
    octave: 'Октава',
    noOctavesSelected: 'Оберіть хоча б одну октаву.',
    noNotesSelected: 'Оберіть хоча б одну ноту.',
    avgTime: 'Сер. час',
    statNote: 'Нота',
    statAccuracy: 'Точність',
    statTime: 'Час',
    sortBy: 'Сортувати',
    sortDifficulty: 'Складність',
    sortName: 'Назва',
    sortTime: 'Час',
    selectInstrument: 'Інструмент',
    instrumentSilence: 'Без звуку',
    instrumentPiano: 'Піаніно',
    instrumentGuitar: 'Гітара',
    instrumentFlute: 'Флейта',
    instrumentMicrophone: 'Мікрофон',
    micAccessRequired: 'Для визначення висоти звуку потрібен доступ до мікрофона.',
    performanceAnalysis: 'Аналіз виконання',
    concealDetails: 'Приховати деталі',
    viewDeepMetrics: 'Глибока аналітика',
    focusOn: 'Фокус на:',
    feedbackMastery: 'Абсолютна майстерність! Ваша точність бездоганна.',
    feedbackExemplary: 'Чудово! Ви стаєте дуже вільним.',
    feedbackProgress: "Відмінний прогрес! Продовжуйте відточувати пам'ять.",
    feedbackGettingThere: 'Вже близько! Зосередьтеся на точності, а не на швидкості.',
    feedbackKeepPracticing: 'Продовжуйте практикуватися! Кожна сесія розвиває навичку.',
    quoteExpert: 'Майстерне виконання! Ваша робота приносить плоди. 🎹',
    quoteStrong: 'Сильний прогрес! Ви будуєте міцний фундамент. 🎵',
    quoteConsistency: 'Постійність — запорука успіху. Продовжуйте грати! ✨',
    reviewProgress: 'Переглянути прогрес',
    backToOverview: 'Повернутися до огляду',
  },
  et: {
    title: 'Noodimeister',
    subtitle: 'Õpi noote lugema',
    setupTitle: 'Seadistus',
    selectLanguage: 'Keel',
    selectClef: 'Võti',
    selectOctaves: 'Vali oktavid',
    selectNotes: 'Vali noodid',
    selectTempo: 'Tempo',
    tempoSlow: 'Aeglane',
    tempoNormal: 'Keskmine',
    tempoFast: 'Kiire',
    startSession: 'Alusta',
    correct: 'Õige',
    total: 'Kokku',
    accuracy: 'Täpsus',
    streak: 'Seeria',
    trebleClef: 'Viiulivõti',
    bassClef: 'Bassivõti',
    question: 'Mis noot see on?',
    playOrSing: 'Mängi või laula',
    playThisNote: 'Mängi seda nooti',
    finishSession: 'Lõpeta',
    resultsTitle: 'Tulemused',
    sessionSummary: 'Hästi tehtud! Siin on sinu tulemused.',
    startNewSession: 'Uus treening',
    correctAnswer: 'Õige!',
    incorrectAnswer: 'Vale. See oli',
    octave: 'Oktav',
    noOctavesSelected: 'Palun vali vähemalt üks oktav.',
    noNotesSelected: 'Palun vali vähemalt üks noot.',
    avgTime: 'Keskm. aeg',
    statNote: 'Noot',
    statAccuracy: 'Täpsus',
    statTime: 'Aeg',
    sortBy: 'Sorteeri',
    sortDifficulty: 'Raskus',
    sortName: 'Nimi',
    sortTime: 'Aeg',
    selectInstrument: 'Vali instrument',
    instrumentSilence: 'Vaikus',
    instrumentPiano: 'Klaver',
    instrumentGuitar: 'Kitarr',
    instrumentFlute: 'Flööt',
    instrumentMicrophone: 'Mikrofon',
    micAccessRequired: 'Helikõrguse tuvastamiseks on vaja juurdepääsu mikrofonile.',
    performanceAnalysis: 'Tulemuslikkuse analüüs',
    concealDetails: 'Peida üksikasjad',
    viewDeepMetrics: 'Vaata süvaanalüüsi',
    focusOn: 'Keskendu:',
    feedbackMastery: 'Täielik meisterlikkus! Sinu täpsus on veatu.',
    feedbackExemplary: 'Eeskujulik! Muutud väga sujuvaks.',
    feedbackProgress: 'Suurepärane areng! Jätka harjutamist.',
    feedbackGettingThere: 'Juba peaaegu! Keskendu täpsusele, mitte kiirusele.',
    feedbackKeepPracticing: 'Jätka harjutamist! Iga seanss arendab oskusi.',
    quoteExpert: 'Meisterlik sooritus! Sinu töö kannab vilja. 🎹',
    quoteStrong: 'Tugev areng! Ehitad kindlat vundamenti. 🎵',
    quoteConsistency: 'Järjepidevus on võti. Jätka mängimist! ✨',
    reviewProgress: 'Vaata edenemist',
    backToOverview: 'Tagasi ülevaatesse',
  },
};

export const NOTE_NAMES: NoteName[] = ['C', 'D', 'E', 'F', 'G', 'A', 'B'];

export const OCTAVE_RANGES = {
  treble: [3, 4, 5, 6],
  bass: [1, 2, 3, 4],
};

export const SUPPORTED_LANGUAGES: Language[] = ['en', 'ru', 'uk', 'et'];
